config/routes.rb
FirstApp::Application.routes.draw do
  resources :bounenkai2015s do
    collection do
      get 'home'
      post 'open_first_box'
      get 'open_second_box'
    end
  end

  root 'bounenkai2015s#home'

  match '/about', 		to: 'static_pages#about', 		via: 'get'
  match '/help', 		to: 'static_pages#help', 		via: 'get'
  match '/contact', 	to: 'static_pages#contact', 	via: 'get'
  match '/signup', 		to: 'users#new', 				via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', 		to: 'sessions#new', 			via: 'get'
  match '/signout', 	to: 'sessions#destroy', 		via: 'delete'
  resources :microposts

  resources :users

end

app/views/layouts/_header.html.erb
<% if false %>

<ul>
<% if signed_in? %>
	<li>Account</li>
	<ul>
	  <li><%= link_to "Users", users_path %></li>
	  <li><%= link_to "Profile", current_user %></li>
	  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
	</ul>
<% else %>
	<li><%= link_to "Sign up", signup_path %></li>
	<li><%= link_to "Sign in", signin_path %></li>
<% end %>
	<li><%= link_to "About", about_path %></li>
	<li><%= link_to "Help", help_path %></li>
	<li><%= link_to "Contact", contact_path %></li>
	<li><%= link_to "Home", root_path %></li>
</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |key, value| %>
	<div id="alert-<%= key %>">
      <div class="alert alert-<%= key %>"><%= value %></div>
	</div>
    <% end %>
	<%= render 'layouts/header' %>
	<%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <%= debug(request.request_method) if Rails.env.development? %>
    <%= debug(request.body) if Rails.env.development? %>
  </body>
</html>